// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-4lyUpm5rQ7yFoI8oEcU8lVel5J8pAE',
    appId: '1:326788551975:web:fdd96c566275b60a128502',
    messagingSenderId: '326788551975',
    projectId: 'undercover-94e92',
    authDomain: 'undercover-94e92.firebaseapp.com',
    storageBucket: 'undercover-94e92.firebasestorage.app',
    measurementId: 'G-BLKWCZH355',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjZbLq-nQZKyy4_3fslI58pJpe7BTp2k',
    appId: '1:326788551975:android:734576ed2f3cd0c2128502',
    messagingSenderId: '326788551975',
    projectId: 'undercover-94e92',
    storageBucket: 'undercover-94e92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKNxwTak8EG5oJwewVPkk__YNTmL54Oc',
    appId: '1:326788551975:ios:c1a2a8004ecee094128502',
    messagingSenderId: '326788551975',
    projectId: 'undercover-94e92',
    storageBucket: 'undercover-94e92.firebasestorage.app',
    iosBundleId: 'com.example.victor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfKNxwTak8EG5oJwewVPkk__YNTmL54Oc',
    appId: '1:326788551975:ios:c1a2a8004ecee094128502',
    messagingSenderId: '326788551975',
    projectId: 'undercover-94e92',
    storageBucket: 'undercover-94e92.firebasestorage.app',
    iosBundleId: 'com.example.victor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO-4lyUpm5rQ7yFoI8oEcU8lVel5J8pAE',
    appId: '1:326788551975:web:8342d1cb4a26f466128502',
    messagingSenderId: '326788551975',
    projectId: 'undercover-94e92',
    authDomain: 'undercover-94e92.firebaseapp.com',
    storageBucket: 'undercover-94e92.firebasestorage.app',
    measurementId: 'G-CWT6RX9B5M',
  );
}
